### ISSUE TITLE
OpenSUSE Tumbleweed opening issue

### ISSUE THREAD

**Issue by dylanlip** [rankynbass/XIVLauncher4rpm#17]
I've become unable to launch the latest Launcher version on Tumbleweed/KDE Wayland (Latest snapshot) w/ kernel 6.0.6 after an update through Copr, then confirmed w/ a fresh rpm & repo install. Launching /usr/bin/xivlauncher gives:

/home/---/.local/bin/xivlauncher-custom.sh: line 2: unexpected EOF while looking for matching `''

Afterwards reinstalled the 1.0.2-1 rpm w/ no errors or issues launching.

**Comment by rankynbass** [comment]
Fixed with update 1.0.2-4. There was a bad line in the launcher script.
