### ISSUE TITLE
Launcher Script does nothing. Faulute to run script, no such file or directory

### ISSUE THREAD

**Issue by scarface96361** [rankynbass/XIVLauncher4rpm#19]
I havent dug too far into this yet due to time issues. however when i try and run the launcher script it ends up erroring out with this message as the final line. |

`/usr/bin/xivlauncher: line 69: /home/scarface96361/.local/bin/xivlauncher-custom.sh: No such file or directory
`

Upon digging in i realized that there isnt a bin folder in my local directory at all. earlier printings in the script return this 

`Creating new file /home/scarface96361/.local/bin/xivlauncher-custom.sh.
/usr/bin/xivlauncher: line 5: /home/scarface96361/.local/bin/xivlauncher-custom.sh: No such file or directory
chmod: cannot access '/home/scarface96361/.local/bin/xivlauncher-custom.sh': No such file or directory
Running script /home/scarface96361/.local/bin/xivlauncher-custom.sh.
`

Im not sure why the script is failing to create the files and directories but it seems to be.

**Comment by scarface96361** [comment]
So, followup. I made a bin folder manually in my .local and the program launched and seems to be running as normal now. So thats a simple fix but i dont believe that the .local folder by default has a bin folder. so the script assuming there is one (or potentially just failing to create it? without looking at the script im not sure) seems like a bit of an oversight. though without looking behind the scenes at the script to see if thats actually the problem i cant be sure. just figured i should at least bring this problem to your attention

**Comment by rankynbass** [comment]
That is exactly the issue. `~/.local/bin` is not being created in 1.0.2-4. It's part of the default `$PATH` in most linux distributions, so I thought it was created during user creation. I'm fixing the script in 1.0.2-5, so the default action will be to just run the launcher, no questions asked. The custom script will be created/accessed separately, so it won't affect normal operation. And the custom launch option will create the `~/.local/bin` folder if it doesn't exist.

**Comment by rankynbass** [comment]
Fixed (hopefully) with 1.0.2-5, out now.
