### ISSUE TITLE
Broken F40 (RB BRANCH)

### ISSUE THREAD

**Issue by xnuken** [rankynbass/XIVLauncher4rpm#24]
Package seems to not work properly on Fedora 40 running the xivlauncher-rb results in the non patched version running. The launch script still points to `/opt/xivlauncher/XIVLauncher.Core` instead of `/opt/xivlauncher-rb/XIVLauncher.Core` and adding `custom` seems to do nothing also.

**Comment by rankynbass** [comment]
Oops. I staged some changes but didn't commit them before pushing. I've pushed out 1.1.0.1, which should fix this. Building on COPR now.
